# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WLReaderDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Moya'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAlamofire'
  pod 'Moya/RxSwift'
  pod 'HandyJSON'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'DTCoreText'
  pod 'SSZipArchive'
  pod 'AEXML'
  pod 'WCDB.swift'
  pod 'YPImagePicker'
  pod 'Popover'
  pod 'Toast-Swift'

  # Pods for WLReaderDemo

  target 'WLReaderDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WLReaderDemoUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
